version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "09:00"
      timezone: Europe/Lisbon
    open-pull-requests-limit: 5
    groups:
      npm-development:
        dependency-type: development
      npm-production:
        dependency-type: production

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "09:00"
      timezone: Europe/Lisbon
    open-pull-requests-limit: 5
