// ESLint 10 flat config (canonical, jvm-OSS standard).
//
//   * @eslint/js recommended  — base JS correctness
//   * typescript-eslint recommended — type-aware TS rules
//   * eslint-plugin-security recommended — flags things like
//     `arr[i]` with non-literal `i`, dynamic-key bracket writes on
//     plain objects, and fs calls with non-literal paths. See #10
//     for the patterns the codebase adopted to satisfy this rule
//     (Map for dynamic-key collections, .at() for state-indexed
//     array access, Reflect.get for single dynamic reads, and
//     per-line // eslint-disable-next-line with a one-line
//     justification for fs-filename on operator-supplied paths).
//
// The security plugin is scoped to `src/**` only (not tests/scripts).
import js from "@eslint/js";
import tseslint from "typescript-eslint";
import security from "eslint-plugin-security";

export default tseslint.config(
  js.configs.recommended,
  ...tseslint.configs.recommended,
  {
    ignores: [
      "dist/**",
      "node_modules/**",
      "coverage/**",
      // Generated by scripts/codegen.ts — never hand-edited.
      "src/generated/**",
    ],
  },
  {
    files: ["**/*.ts", "**/*.tsx"],
    languageOptions: {
      parserOptions: {
        projectService: true,
        tsconfigRootDir: import.meta.dirname,
      },
    },
    rules: {
      "@typescript-eslint/no-explicit-any": "off",
      "@typescript-eslint/no-unused-vars": [
        "error",
        { argsIgnorePattern: "^_" },
      ],
    },
  },
  {
    // Security plugin only on shipped code, not on tests/scripts.
    // Tests intentionally write fixtures and introspect request bodies;
    // scripts are dev-only tooling. The user-facing surface is src/.
    files: ["src/**/*.ts", "src/**/*.tsx"],
    plugins: { security },
    rules: { ...security.configs.recommended.rules },
  },
);
